// Generated by https://quicktype.io

export interface IEmpleados {
    dni:              string;
    nombre:           string;
    apellidos:        string;
    email:            string;
    fecha_nacimiento: string;
    telefono:         string;
}
