// Generated by https://quicktype.io

export interface IUsuarios {
    id?: number;
    fullName: string;
    email: string;
    password: string;
    isActive?: boolean;
    token?: string;
    roles?: string[]
}
