// Generated by https://quicktype.io

export interface IUsuarios {
    dni:      string;
    fullname: string;
    username: string;
    email:    string;
    password: string;
    roles:    string[];
    isActive: boolean;
}
